service: stone-challenge-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SALT: FRCTcXr2rxMH2igAvYh5M8tCCe1C5Qho
    JWT_SECRET: 629a7c8b08ed042a9f2e87300af24e0c

functions:
  showTonVisitCount:
    handler: api/handlers.showTonVisitCount
    events:
      - httpApi:
          path: /show-ton-visit-count
          method: get
  incrementTonVisitCount:
    handler: api/handlers.incrementTonVisitCount
    events:
      - httpApi:
          path: /increment-ton-visit-count
          method: get
  addNewUser:
    handler: api/handlers.addNewUser
    events:
      - httpApi:
          path: /add-new-user
          method: post
  searchUserById:
    handler: api/handlers.searchUserById
    events:
      - httpApi:
          path: /search-user-by-id/{id}
          method: get
  userLogin:
    handler: api/handlers.userLogin
    events:
      - httpApi:
          path: /user-login
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/userLogin.json)}

plugins:
  - serverless-offline