service: stone-challenge-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  showTonVisitCount:
    handler: api/handlers.showTonVisitCount
    events:
      - httpApi:
          path: /show-ton-visit-count
          method: get
  incrementTonVisitCount:
    handler: api/handlers.incrementTonVisitCount
    events:
      - httpApi:
          path: /increment-ton-visit-count
          method: get
plugins:
  - serverless-offline
